// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

type ApplyNamedNetworkRequest struct {
	// the namednetwork ID
	Namednetworkid string `pathParam:"style=simple,explode=false,name=namednetworkid"`
	// the asset ID to apply the namednetwork to
	Assetid string `pathParam:"style=simple,explode=false,name=assetid"`
	// namednetwork input
	NamedNetworkInput shared.NamedNetworkInput `request:"mediaType=application/json"`
}

func (o *ApplyNamedNetworkRequest) GetNamednetworkid() string {
	if o == nil {
		return ""
	}
	return o.Namednetworkid
}

func (o *ApplyNamedNetworkRequest) GetAssetid() string {
	if o == nil {
		return ""
	}
	return o.Assetid
}

func (o *ApplyNamedNetworkRequest) GetNamedNetworkInput() shared.NamedNetworkInput {
	if o == nil {
		return shared.NamedNetworkInput{}
	}
	return o.NamedNetworkInput
}

type ApplyNamedNetworkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad Request
	ErrorResponse *shared.ErrorResponse
	Headers       map[string][]string
}

func (o *ApplyNamedNetworkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ApplyNamedNetworkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ApplyNamedNetworkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ApplyNamedNetworkResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *ApplyNamedNetworkResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
