// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

type DeleteFromNamedNetworkRequest struct {
	// the NamedNetwork ID
	NamedNetworkID string `pathParam:"style=simple,explode=false,name=namedNetworkId"`
	// named network ranges
	RequestBody []shared.NamednetworkRange `request:"mediaType=application/json"`
}

func (o *DeleteFromNamedNetworkRequest) GetNamedNetworkID() string {
	if o == nil {
		return ""
	}
	return o.NamedNetworkID
}

func (o *DeleteFromNamedNetworkRequest) GetRequestBody() []shared.NamednetworkRange {
	if o == nil {
		return []shared.NamednetworkRange{}
	}
	return o.RequestBody
}

type DeleteFromNamedNetworkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad Request
	ErrorResponse *shared.ErrorResponse
	Headers       map[string][]string
}

func (o *DeleteFromNamedNetworkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteFromNamedNetworkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteFromNamedNetworkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteFromNamedNetworkResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *DeleteFromNamedNetworkResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
