// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"net/http"
)

type DeleteFromTemplateRequest struct {
	// the template ID
	Templateid string `pathParam:"style=simple,explode=false,name=templateid"`
	// template rule ids
	APITemplatePayloadHashes shared.APITemplatePayloadHashes `request:"mediaType=application/json"`
}

func (o *DeleteFromTemplateRequest) GetTemplateid() string {
	if o == nil {
		return ""
	}
	return o.Templateid
}

func (o *DeleteFromTemplateRequest) GetAPITemplatePayloadHashes() shared.APITemplatePayloadHashes {
	if o == nil {
		return shared.APITemplatePayloadHashes{}
	}
	return o.APITemplatePayloadHashes
}

type DeleteFromTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *DeleteFromTemplateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteFromTemplateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteFromTemplateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteFromTemplateResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
