// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

type GetFieldRequest struct {
	// fieldId
	FieldID string `pathParam:"style=simple,explode=false,name=fieldId"`
}

func (o *GetFieldRequest) GetFieldID() string {
	if o == nil {
		return ""
	}
	return o.FieldID
}

type GetFieldResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	MetadataColumnDescriptor *shared.MetadataColumnDescriptor
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *GetFieldResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetFieldResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetFieldResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetFieldResponse) GetMetadataColumnDescriptor() *shared.MetadataColumnDescriptor {
	if o == nil {
		return nil
	}
	return o.MetadataColumnDescriptor
}

func (o *GetFieldResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
