// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

type GetNamedNetworkRequest struct {
	// Named Network ID
	NamedNetworkID string `pathParam:"style=simple,explode=false,name=namedNetworkId"`
}

func (o *GetNamedNetworkRequest) GetNamedNetworkID() string {
	if o == nil {
		return ""
	}
	return o.NamedNetworkID
}

type GetNamedNetworkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	NamednetworkNamedNetwork *shared.NamednetworkNamedNetwork
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *GetNamedNetworkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetNamedNetworkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetNamedNetworkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetNamedNetworkResponse) GetNamednetworkNamedNetwork() *shared.NamednetworkNamedNetwork {
	if o == nil {
		return nil
	}
	return o.NamednetworkNamedNetwork
}

func (o *GetNamedNetworkResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
