// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"net/http"
)

type GetTemplateRequest struct {
	// the template ID
	Templateid string `pathParam:"style=simple,explode=false,name=templateid"`
}

func (o *GetTemplateRequest) GetTemplateid() string {
	if o == nil {
		return ""
	}
	return o.Templateid
}

type GetTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Template *shared.Template
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *GetTemplateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTemplateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTemplateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetTemplateResponse) GetTemplate() *shared.Template {
	if o == nil {
		return nil
	}
	return o.Template
}

func (o *GetTemplateResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
