// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

type GetTagRuleAssetsRequest struct {
	// TagRule ID
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
}

func (o *GetTagRuleAssetsRequest) GetRuleID() string {
	if o == nil {
		return ""
	}
	return o.RuleID
}

type GetTagRuleAssetsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	MembershipList *shared.MembershipList
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *GetTagRuleAssetsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTagRuleAssetsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTagRuleAssetsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetTagRuleAssetsResponse) GetMembershipList() *shared.MembershipList {
	if o == nil {
		return nil
	}
	return o.MembershipList
}

func (o *GetTagRuleAssetsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
