// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

type GetTagBasedPolicyRequest struct {
	// Tag ID
	TagbasedpolicyID string `pathParam:"style=simple,explode=false,name=tagbasedpolicyId"`
}

func (o *GetTagBasedPolicyRequest) GetTagbasedpolicyID() string {
	if o == nil {
		return ""
	}
	return o.TagbasedpolicyID
}

type GetTagBasedPolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TagBasedPolicy *shared.TagBasedPolicy
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *GetTagBasedPolicyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTagBasedPolicyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTagBasedPolicyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetTagBasedPolicyResponse) GetTagBasedPolicy() *shared.TagBasedPolicy {
	if o == nil {
		return nil
	}
	return o.TagBasedPolicy
}

func (o *GetTagBasedPolicyResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
