// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

type ListFirewallRulesSnapshotsRequest struct {
	// assetId to list firewall state files for
	AssetID string `pathParam:"style=simple,explode=false,name=assetId"`
}

func (o *ListFirewallRulesSnapshotsRequest) GetAssetID() string {
	if o == nil {
		return ""
	}
	return o.AssetID
}

type ListFirewallRulesSnapshotsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	FileList *shared.FileList
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *ListFirewallRulesSnapshotsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListFirewallRulesSnapshotsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListFirewallRulesSnapshotsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListFirewallRulesSnapshotsResponse) GetFileList() *shared.FileList {
	if o == nil {
		return nil
	}
	return o.FileList
}

func (o *ListFirewallRulesSnapshotsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
