// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"net/http"
)

type ListEventsRequest struct {
	// file download
	Download *string `queryParam:"style=form,explode=true,name=download"`
	// search details
	SearchInput shared.SearchInput `request:"mediaType=application/json"`
}

func (o *ListEventsRequest) GetDownload() *string {
	if o == nil {
		return nil
	}
	return o.Download
}

func (o *ListEventsRequest) GetSearchInput() shared.SearchInput {
	if o == nil {
		return shared.SearchInput{}
	}
	return o.SearchInput
}

type ListEventsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	EventSearchResults *shared.EventSearchResults
	Body               []byte
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *ListEventsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListEventsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListEventsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListEventsResponse) GetEventSearchResults() *shared.EventSearchResults {
	if o == nil {
		return nil
	}
	return o.EventSearchResults
}

func (o *ListEventsResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *ListEventsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
