// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

// QueryParamSortField - field name to use for sorting.
type QueryParamSortField string

const (
	QueryParamSortFieldName  QueryParamSortField = "name"
	QueryParamSortFieldValue QueryParamSortField = "value"
)

func (e QueryParamSortField) ToPointer() *QueryParamSortField {
	return &e
}
func (e *QueryParamSortField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "name":
		fallthrough
	case "value":
		*e = QueryParamSortField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamSortField: %v", v)
	}
}

// QueryParamSortOrder - Either ascending or descending ordering for the specified sortField
type QueryParamSortOrder string

const (
	QueryParamSortOrderAscending  QueryParamSortOrder = "ascending"
	QueryParamSortOrderDescending QueryParamSortOrder = "descending"
)

func (e QueryParamSortOrder) ToPointer() *QueryParamSortOrder {
	return &e
}
func (e *QueryParamSortOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ascending":
		fallthrough
	case "descending":
		*e = QueryParamSortOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamSortOrder: %v", v)
	}
}

type ListTagsRequest struct {
	// name search using equality
	Name []string `queryParam:"style=form,explode=true,name=name"`
	// value search using equality
	Value []string `queryParam:"style=form,explode=true,name=value"`
	// field name to use for sorting.
	SortField *QueryParamSortField `queryParam:"style=form,explode=true,name=sortField"`
	// Either ascending or descending ordering for the specified sortField
	SortOrder *QueryParamSortOrder `queryParam:"style=form,explode=true,name=sortOrder"`
	// Number of items to return per page if number of matches found exceeds this then pagination will be required to access all results
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Starting position in results
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *ListTagsRequest) GetName() []string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ListTagsRequest) GetValue() []string {
	if o == nil {
		return nil
	}
	return o.Value
}

func (o *ListTagsRequest) GetSortField() *QueryParamSortField {
	if o == nil {
		return nil
	}
	return o.SortField
}

func (o *ListTagsRequest) GetSortOrder() *QueryParamSortOrder {
	if o == nil {
		return nil
	}
	return o.SortOrder
}

func (o *ListTagsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListTagsRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type ListTagsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Tags *shared.Tags
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *ListTagsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListTagsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListTagsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListTagsResponse) GetTags() *shared.Tags {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *ListTagsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
