// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

type ListVulnerabilitiesRequest struct {
	// Asset ID
	AssetID string `pathParam:"style=simple,explode=false,name=assetId"`
	// vulnerabilities request
	VulnerabilitiesRequestData shared.VulnerabilitiesRequestData `request:"mediaType=application/json"`
}

func (o *ListVulnerabilitiesRequest) GetAssetID() string {
	if o == nil {
		return ""
	}
	return o.AssetID
}

func (o *ListVulnerabilitiesRequest) GetVulnerabilitiesRequestData() shared.VulnerabilitiesRequestData {
	if o == nil {
		return shared.VulnerabilitiesRequestData{}
	}
	return o.VulnerabilitiesRequestData
}

type ListVulnerabilitiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CVEDataResults *shared.CVEDataResults
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *ListVulnerabilitiesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListVulnerabilitiesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListVulnerabilitiesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListVulnerabilitiesResponse) GetCVEDataResults() *shared.CVEDataResults {
	if o == nil {
		return nil
	}
	return o.CVEDataResults
}

func (o *ListVulnerabilitiesResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
