// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

type SynchronizeAssetZeroTrustRequest struct {
	// Asset ID
	AssetID string `pathParam:"style=simple,explode=false,name=assetId"`
	// input for synchronization
	AssetSynchronization shared.AssetSynchronization `request:"mediaType=application/json"`
}

func (o *SynchronizeAssetZeroTrustRequest) GetAssetID() string {
	if o == nil {
		return ""
	}
	return o.AssetID
}

func (o *SynchronizeAssetZeroTrustRequest) GetAssetSynchronization() shared.AssetSynchronization {
	if o == nil {
		return shared.AssetSynchronization{}
	}
	return o.AssetSynchronization
}

type SynchronizeAssetZeroTrustResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Accepted. Async processing in-progress and can be tracked using value in header 'x-ct-workrequest-id'
	TwoHundredAndTwoApplicationJSONString *string
	// Not Modified
	ThreeHundredAndFourApplicationJSONString *string
	// Bad Request
	ErrorResponse *shared.ErrorResponse
	Headers       map[string][]string
}

func (o *SynchronizeAssetZeroTrustResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SynchronizeAssetZeroTrustResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SynchronizeAssetZeroTrustResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *SynchronizeAssetZeroTrustResponse) GetTwoHundredAndTwoApplicationJSONString() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredAndTwoApplicationJSONString
}

func (o *SynchronizeAssetZeroTrustResponse) GetThreeHundredAndFourApplicationJSONString() *string {
	if o == nil {
		return nil
	}
	return o.ThreeHundredAndFourApplicationJSONString
}

func (o *SynchronizeAssetZeroTrustResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *SynchronizeAssetZeroTrustResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
