// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"net/http"
)

type UpdateAssetRequest struct {
	// Asset ID
	AssetID string `pathParam:"style=simple,explode=false,name=assetId"`
	// asset definition
	CreateAssetDetails shared.CreateAssetDetails `request:"mediaType=application/json"`
}

func (o *UpdateAssetRequest) GetAssetID() string {
	if o == nil {
		return ""
	}
	return o.AssetID
}

func (o *UpdateAssetRequest) GetCreateAssetDetails() shared.CreateAssetDetails {
	if o == nil {
		return shared.CreateAssetDetails{}
	}
	return o.CreateAssetDetails
}

type UpdateAssetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	AssetDetails *shared.AssetDetails
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *UpdateAssetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateAssetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateAssetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateAssetResponse) GetAssetDetails() *shared.AssetDetails {
	if o == nil {
		return nil
	}
	return o.AssetDetails
}

func (o *UpdateAssetResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
