// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/colortokens/terraform-provider-xshield/internal/sdk/models/shared"
	"net/http"
)

type UpdateFieldRequest struct {
	// fieldId
	FieldID string `pathParam:"style=simple,explode=false,name=fieldId"`
	// field details
	Field shared.Field `request:"mediaType=application/json"`
}

func (o *UpdateFieldRequest) GetFieldID() string {
	if o == nil {
		return ""
	}
	return o.FieldID
}

func (o *UpdateFieldRequest) GetField() shared.Field {
	if o == nil {
		return shared.Field{}
	}
	return o.Field
}

type UpdateFieldResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	MetadataColumnDescriptor *shared.MetadataColumnDescriptor
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *UpdateFieldResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateFieldResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateFieldResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateFieldResponse) GetMetadataColumnDescriptor() *shared.MetadataColumnDescriptor {
	if o == nil {
		return nil
	}
	return o.MetadataColumnDescriptor
}

func (o *UpdateFieldResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
