// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AssetGroup definition
type AssetGroup struct {
	Groupid *string `json:"groupid,omitempty"`
}

func (o *AssetGroup) GetGroupid() *string {
	if o == nil {
		return nil
	}
	return o.Groupid
}
