// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type BulkAssetAnnotationDetailsBusinessValue string

const (
	BulkAssetAnnotationDetailsBusinessValueHigh   BulkAssetAnnotationDetailsBusinessValue = "high"
	BulkAssetAnnotationDetailsBusinessValueMedium BulkAssetAnnotationDetailsBusinessValue = "medium"
	BulkAssetAnnotationDetailsBusinessValueLow    BulkAssetAnnotationDetailsBusinessValue = "low"
)

func (e BulkAssetAnnotationDetailsBusinessValue) ToPointer() *BulkAssetAnnotationDetailsBusinessValue {
	return &e
}
func (e *BulkAssetAnnotationDetailsBusinessValue) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "high":
		fallthrough
	case "medium":
		fallthrough
	case "low":
		*e = BulkAssetAnnotationDetailsBusinessValue(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BulkAssetAnnotationDetailsBusinessValue: %v", v)
	}
}

// BulkAssetAnnotationDetails definition Allows update/setting of user modifiable attributes for an asset.
type BulkAssetAnnotationDetails struct {
	BusinessValue *BulkAssetAnnotationDetailsBusinessValue `json:"businessValue,omitempty"`
	CoreTags      map[string]string                        `json:"coreTags,omitempty"`
	Criteria      string                                   `json:"criteria"`
	OsName        *string                                  `json:"osName,omitempty"`
	VendorInfo    *string                                  `json:"vendorInfo,omitempty"`
}

func (o *BulkAssetAnnotationDetails) GetBusinessValue() *BulkAssetAnnotationDetailsBusinessValue {
	if o == nil {
		return nil
	}
	return o.BusinessValue
}

func (o *BulkAssetAnnotationDetails) GetCoreTags() map[string]string {
	if o == nil {
		return nil
	}
	return o.CoreTags
}

func (o *BulkAssetAnnotationDetails) GetCriteria() string {
	if o == nil {
		return ""
	}
	return o.Criteria
}

func (o *BulkAssetAnnotationDetails) GetOsName() *string {
	if o == nil {
		return nil
	}
	return o.OsName
}

func (o *BulkAssetAnnotationDetails) GetVendorInfo() *string {
	if o == nil {
		return nil
	}
	return o.VendorInfo
}
