// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BulkDeleteAssetsInput struct {
	AssetIDList []string `json:"assetIDList,omitempty"`
}

func (o *BulkDeleteAssetsInput) GetAssetIDList() []string {
	if o == nil {
		return nil
	}
	return o.AssetIDList
}
