// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CloneOptions struct {
	AccessPolicies *bool `json:"accessPolicies,omitempty"`
	Automation     *bool `json:"automation,omitempty"`
	Namednetworks  *bool `json:"namednetworks,omitempty"`
	Progressive    *bool `json:"progressive,omitempty"`
	Templates      *bool `json:"templates,omitempty"`
}

func (o *CloneOptions) GetAccessPolicies() *bool {
	if o == nil {
		return nil
	}
	return o.AccessPolicies
}

func (o *CloneOptions) GetAutomation() *bool {
	if o == nil {
		return nil
	}
	return o.Automation
}

func (o *CloneOptions) GetNamednetworks() *bool {
	if o == nil {
		return nil
	}
	return o.Namednetworks
}

func (o *CloneOptions) GetProgressive() *bool {
	if o == nil {
		return nil
	}
	return o.Progressive
}

func (o *CloneOptions) GetTemplates() *bool {
	if o == nil {
		return nil
	}
	return o.Templates
}
