// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/internal/utils"
	"time"
)

// Event - Events definition Core resource providing logical representation of an Events
type Event struct {
	Action   *string `json:"action,omitempty"`
	ActionBy *string `json:"actionBy,omitempty"`
	// AssetSummary definition Summary of host or application running on a host that can be observed to apply segmentation policies against
	Asset         *AssetSummary `json:"asset,omitempty"`
	CreationTime  *time.Time    `json:"creationTime,omitempty"`
	EventCategory *string       `json:"eventCategory,omitempty"`
	EventType     *string       `json:"eventType,omitempty"`
	Message       *string       `json:"message,omitempty"`
	Metadata      *string       `json:"metadata,omitempty"`
	ResourceID    *string       `json:"resourceId,omitempty"`
	Severity      *string       `json:"severity,omitempty"`
	SourceIP      *string       `json:"sourceIp,omitempty"`
}

func (e Event) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Event) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Event) GetAction() *string {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *Event) GetActionBy() *string {
	if o == nil {
		return nil
	}
	return o.ActionBy
}

func (o *Event) GetAsset() *AssetSummary {
	if o == nil {
		return nil
	}
	return o.Asset
}

func (o *Event) GetCreationTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreationTime
}

func (o *Event) GetEventCategory() *string {
	if o == nil {
		return nil
	}
	return o.EventCategory
}

func (o *Event) GetEventType() *string {
	if o == nil {
		return nil
	}
	return o.EventType
}

func (o *Event) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *Event) GetMetadata() *string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *Event) GetResourceID() *string {
	if o == nil {
		return nil
	}
	return o.ResourceID
}

func (o *Event) GetSeverity() *string {
	if o == nil {
		return nil
	}
	return o.Severity
}

func (o *Event) GetSourceIP() *string {
	if o == nil {
		return nil
	}
	return o.SourceIP
}
