// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Field struct {
	DisplayName *string `json:"displayName,omitempty"`
}

func (o *Field) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}
