// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type MetadataTagBasedPolicyReference struct {
	Criteria           *string `json:"criteria,omitempty"`
	TagBasedPolicyID   *string `json:"tagBasedPolicyId,omitempty"`
	TagBasedPolicyName *string `json:"tagBasedPolicyName,omitempty"`
}

func (o *MetadataTagBasedPolicyReference) GetCriteria() *string {
	if o == nil {
		return nil
	}
	return o.Criteria
}

func (o *MetadataTagBasedPolicyReference) GetTagBasedPolicyID() *string {
	if o == nil {
		return nil
	}
	return o.TagBasedPolicyID
}

func (o *MetadataTagBasedPolicyReference) GetTagBasedPolicyName() *string {
	if o == nil {
		return nil
	}
	return o.TagBasedPolicyName
}
