// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type MetricResults struct {
	Items map[string]any `json:"items,omitempty"`
}

func (o *MetricResults) GetItems() map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}
