// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MetricSearchInput struct {
	Criteria            string   `json:"criteria"`
	DestinationCriteria *string  `json:"destinationCriteria,omitempty"`
	GroupBy             []string `json:"groupBy,omitempty"`
	Scope               *string  `json:"scope,omitempty"`
	SourceCriteria      *string  `json:"sourceCriteria,omitempty"`
	Statistics          []string `json:"statistics,omitempty"`
	TimeEnd             *string  `json:"timeEnd,omitempty"`
	TimeStart           *string  `json:"timeStart,omitempty"`
}

func (o *MetricSearchInput) GetCriteria() string {
	if o == nil {
		return ""
	}
	return o.Criteria
}

func (o *MetricSearchInput) GetDestinationCriteria() *string {
	if o == nil {
		return nil
	}
	return o.DestinationCriteria
}

func (o *MetricSearchInput) GetGroupBy() []string {
	if o == nil {
		return nil
	}
	return o.GroupBy
}

func (o *MetricSearchInput) GetScope() *string {
	if o == nil {
		return nil
	}
	return o.Scope
}

func (o *MetricSearchInput) GetSourceCriteria() *string {
	if o == nil {
		return nil
	}
	return o.SourceCriteria
}

func (o *MetricSearchInput) GetStatistics() []string {
	if o == nil {
		return nil
	}
	return o.Statistics
}

func (o *MetricSearchInput) GetTimeEnd() *string {
	if o == nil {
		return nil
	}
	return o.TimeEnd
}

func (o *MetricSearchInput) GetTimeStart() *string {
	if o == nil {
		return nil
	}
	return o.TimeStart
}
