// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NamedNetworkInput struct {
	Comment *string `json:"comment,omitempty"`
}

func (o *NamedNetworkInput) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}
