// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NetworkMapSearchInput struct {
	Criteria            string   `json:"criteria"`
	DestinationCriteria *string  `json:"destinationCriteria,omitempty"`
	GroupBy             []string `json:"groupBy,omitempty"`
	Scope               *string  `json:"scope,omitempty"`
	SourceCriteria      *string  `json:"sourceCriteria,omitempty"`
	Statistics          []string `json:"statistics,omitempty"`
	TimeEnd             *string  `json:"timeEnd,omitempty"`
	TimeStart           *string  `json:"timeStart,omitempty"`
}

func (o *NetworkMapSearchInput) GetCriteria() string {
	if o == nil {
		return ""
	}
	return o.Criteria
}

func (o *NetworkMapSearchInput) GetDestinationCriteria() *string {
	if o == nil {
		return nil
	}
	return o.DestinationCriteria
}

func (o *NetworkMapSearchInput) GetGroupBy() []string {
	if o == nil {
		return nil
	}
	return o.GroupBy
}

func (o *NetworkMapSearchInput) GetScope() *string {
	if o == nil {
		return nil
	}
	return o.Scope
}

func (o *NetworkMapSearchInput) GetSourceCriteria() *string {
	if o == nil {
		return nil
	}
	return o.SourceCriteria
}

func (o *NetworkMapSearchInput) GetStatistics() []string {
	if o == nil {
		return nil
	}
	return o.Statistics
}

func (o *NetworkMapSearchInput) GetTimeEnd() *string {
	if o == nil {
		return nil
	}
	return o.TimeEnd
}

func (o *NetworkMapSearchInput) GetTimeStart() *string {
	if o == nil {
		return nil
	}
	return o.TimeStart
}
