// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ObjectstorageBlob struct {
	LastModified *string `json:"lastModified,omitempty"`
	Name         *string `json:"name,omitempty"`
	SizeInBytes  *int64  `json:"sizeInBytes,omitempty"`
}

func (o *ObjectstorageBlob) GetLastModified() *string {
	if o == nil {
		return nil
	}
	return o.LastModified
}

func (o *ObjectstorageBlob) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ObjectstorageBlob) GetSizeInBytes() *int64 {
	if o == nil {
		return nil
	}
	return o.SizeInBytes
}
