// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OrderBy struct {
	Field *string    `json:"field,omitempty"`
	Order *SortOrder `json:"order,omitempty"`
}

func (o *OrderBy) GetField() *string {
	if o == nil {
		return nil
	}
	return o.Field
}

func (o *OrderBy) GetOrder() *SortOrder {
	if o == nil {
		return nil
	}
	return o.Order
}
