// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PaginationInfo struct {
	HasMore *bool  `json:"hasMore,omitempty"`
	Limit   *int64 `json:"limit,omitempty"`
	Offset  *int64 `json:"offset,omitempty"`
}

func (o *PaginationInfo) GetHasMore() *bool {
	if o == nil {
		return nil
	}
	return o.HasMore
}

func (o *PaginationInfo) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PaginationInfo) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}
