// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PathsNamedNetworkRecommendation struct {
	NamedNetwork      *MetadataNamedNetworkReference `json:"namedNetwork,omitempty"`
	PeerCount         *int64                         `json:"peerCount,omitempty"`
	TotalAddressCount *int64                         `json:"totalAddressCount,omitempty"`
}

func (o *PathsNamedNetworkRecommendation) GetNamedNetwork() *MetadataNamedNetworkReference {
	if o == nil {
		return nil
	}
	return o.NamedNetwork
}

func (o *PathsNamedNetworkRecommendation) GetPeerCount() *int64 {
	if o == nil {
		return nil
	}
	return o.PeerCount
}

func (o *PathsNamedNetworkRecommendation) GetTotalAddressCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalAddressCount
}
