// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PathSearchInput struct {
	Criteria            string            `json:"criteria"`
	DestinationCriteria *string           `json:"destinationCriteria,omitempty"`
	FacetFields         []string          `json:"facetFields,omitempty"`
	Pagination          *PaginationConfig `json:"pagination,omitempty"`
	SourceCriteria      *string           `json:"sourceCriteria,omitempty"`
}

func (o *PathSearchInput) GetCriteria() string {
	if o == nil {
		return ""
	}
	return o.Criteria
}

func (o *PathSearchInput) GetDestinationCriteria() *string {
	if o == nil {
		return nil
	}
	return o.DestinationCriteria
}

func (o *PathSearchInput) GetFacetFields() []string {
	if o == nil {
		return nil
	}
	return o.FacetFields
}

func (o *PathSearchInput) GetPagination() *PaginationConfig {
	if o == nil {
		return nil
	}
	return o.Pagination
}

func (o *PathSearchInput) GetSourceCriteria() *string {
	if o == nil {
		return nil
	}
	return o.SourceCriteria
}
