// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PendingChanges struct {
	AllowTemplates           []string `json:"allowTemplates,omitempty"`
	BlockTemplates           []string `json:"blockTemplates,omitempty"`
	InternetPaths            *int64   `json:"internetPaths,omitempty"`
	InternetPorts            *int64   `json:"internetPorts,omitempty"`
	IntranetChange           []string `json:"intranetChange,omitempty"`
	IntranetPaths            *int64   `json:"intranetPaths,omitempty"`
	IntranetPorts            *int64   `json:"intranetPorts,omitempty"`
	NamednetworkChange       []string `json:"namednetworkChange,omitempty"`
	ProgressiveSyncPending   *bool    `json:"progressiveSyncPending,omitempty"`
	UnassignedAllowTemplates []string `json:"unassignedAllowTemplates,omitempty"`
	UnassignedBlockTemplates []string `json:"unassignedBlockTemplates,omitempty"`
}

func (o *PendingChanges) GetAllowTemplates() []string {
	if o == nil {
		return nil
	}
	return o.AllowTemplates
}

func (o *PendingChanges) GetBlockTemplates() []string {
	if o == nil {
		return nil
	}
	return o.BlockTemplates
}

func (o *PendingChanges) GetInternetPaths() *int64 {
	if o == nil {
		return nil
	}
	return o.InternetPaths
}

func (o *PendingChanges) GetInternetPorts() *int64 {
	if o == nil {
		return nil
	}
	return o.InternetPorts
}

func (o *PendingChanges) GetIntranetChange() []string {
	if o == nil {
		return nil
	}
	return o.IntranetChange
}

func (o *PendingChanges) GetIntranetPaths() *int64 {
	if o == nil {
		return nil
	}
	return o.IntranetPaths
}

func (o *PendingChanges) GetIntranetPorts() *int64 {
	if o == nil {
		return nil
	}
	return o.IntranetPorts
}

func (o *PendingChanges) GetNamednetworkChange() []string {
	if o == nil {
		return nil
	}
	return o.NamednetworkChange
}

func (o *PendingChanges) GetProgressiveSyncPending() *bool {
	if o == nil {
		return nil
	}
	return o.ProgressiveSyncPending
}

func (o *PendingChanges) GetUnassignedAllowTemplates() []string {
	if o == nil {
		return nil
	}
	return o.UnassignedAllowTemplates
}

func (o *PendingChanges) GetUnassignedBlockTemplates() []string {
	if o == nil {
		return nil
	}
	return o.UnassignedBlockTemplates
}
