// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type StateTransitionInput struct {
	Comment *string `json:"comment,omitempty"`
	ToState string  `json:"toState"`
}

func (o *StateTransitionInput) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}

func (o *StateTransitionInput) GetToState() string {
	if o == nil {
		return ""
	}
	return o.ToState
}
