// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TagBasedPolicies struct {
	Items    []TagBasedPolicySummary `json:"items,omitempty"`
	Metadata *PaginationSummary      `json:"metadata,omitempty"`
}

func (o *TagBasedPolicies) GetItems() []TagBasedPolicySummary {
	if o == nil {
		return nil
	}
	return o.Items
}

func (o *TagBasedPolicies) GetMetadata() *PaginationSummary {
	if o == nil {
		return nil
	}
	return o.Metadata
}
