// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TemplateBodyWithComment struct {
	Comment       *string        `json:"comment,omitempty"`
	TemplatePaths []MetadataPath `json:"templatePaths,omitempty"`
	TemplatePorts []MetadataPort `json:"templatePorts,omitempty"`
}

func (o *TemplateBodyWithComment) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}

func (o *TemplateBodyWithComment) GetTemplatePaths() []MetadataPath {
	if o == nil {
		return nil
	}
	return o.TemplatePaths
}

func (o *TemplateBodyWithComment) GetTemplatePorts() []MetadataPort {
	if o == nil {
		return nil
	}
	return o.TemplatePorts
}
