// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TemplateSummary struct {
	AccessPolicyTemplate                            *bool   `json:"accessPolicyTemplate,omitempty"`
	AssignedByTagBasedPolicy                        *bool   `json:"assignedByTagBasedPolicy,omitempty"`
	OobTemplate                                     *bool   `json:"oobTemplate,omitempty"`
	TemplateAssignments                             *int64  `json:"templateAssignments,omitempty"`
	TemplateCategory                                *string `json:"templateCategory,omitempty"`
	TemplateDescription                             *string `json:"templateDescription,omitempty"`
	TemplateID                                      *string `json:"templateId,omitempty"`
	TemplateName                                    *string `json:"templateName,omitempty"`
	TemplatePaths                                   *int64  `json:"templatePaths,omitempty"`
	TemplatePorts                                   *int64  `json:"templatePorts,omitempty"`
	TemplateTagBasedPolicyAssignments               *int64  `json:"templateTagBasedPolicyAssignments,omitempty"`
	TemplateType                                    string  `json:"templateType"`
	TemplateUnassignmentsPendingFirewallSynchronize *int64  `json:"templateUnassignmentsPendingFirewallSynchronize,omitempty"`
	TotalComments                                   *int64  `json:"totalComments,omitempty"`
	UsergroupTemplateAssignments                    *int64  `json:"usergroupTemplateAssignments,omitempty"`
}

func (o *TemplateSummary) GetAccessPolicyTemplate() *bool {
	if o == nil {
		return nil
	}
	return o.AccessPolicyTemplate
}

func (o *TemplateSummary) GetAssignedByTagBasedPolicy() *bool {
	if o == nil {
		return nil
	}
	return o.AssignedByTagBasedPolicy
}

func (o *TemplateSummary) GetOobTemplate() *bool {
	if o == nil {
		return nil
	}
	return o.OobTemplate
}

func (o *TemplateSummary) GetTemplateAssignments() *int64 {
	if o == nil {
		return nil
	}
	return o.TemplateAssignments
}

func (o *TemplateSummary) GetTemplateCategory() *string {
	if o == nil {
		return nil
	}
	return o.TemplateCategory
}

func (o *TemplateSummary) GetTemplateDescription() *string {
	if o == nil {
		return nil
	}
	return o.TemplateDescription
}

func (o *TemplateSummary) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *TemplateSummary) GetTemplateName() *string {
	if o == nil {
		return nil
	}
	return o.TemplateName
}

func (o *TemplateSummary) GetTemplatePaths() *int64 {
	if o == nil {
		return nil
	}
	return o.TemplatePaths
}

func (o *TemplateSummary) GetTemplatePorts() *int64 {
	if o == nil {
		return nil
	}
	return o.TemplatePorts
}

func (o *TemplateSummary) GetTemplateTagBasedPolicyAssignments() *int64 {
	if o == nil {
		return nil
	}
	return o.TemplateTagBasedPolicyAssignments
}

func (o *TemplateSummary) GetTemplateType() string {
	if o == nil {
		return ""
	}
	return o.TemplateType
}

func (o *TemplateSummary) GetTemplateUnassignmentsPendingFirewallSynchronize() *int64 {
	if o == nil {
		return nil
	}
	return o.TemplateUnassignmentsPendingFirewallSynchronize
}

func (o *TemplateSummary) GetTotalComments() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalComments
}

func (o *TemplateSummary) GetUsergroupTemplateAssignments() *int64 {
	if o == nil {
		return nil
	}
	return o.UsergroupTemplateAssignments
}
