// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Template struct {
	AccessPolicyTemplate *bool          `json:"accessPolicyTemplate,omitempty"`
	ColortokensManaged   *bool          `json:"oobTemplate,omitempty"`
	TemplateCategory     *string        `json:"templateCategory,omitempty"`
	TemplateDescription  *string        `json:"templateDescription,omitempty"`
	ID                   *string        `json:"templateId,omitempty"`
	TemplateName         *string        `json:"templateName,omitempty"`
	TemplatePaths        []TemplatePath `json:"templatePaths,omitempty"`
	TemplatePorts        []MetadataPort `json:"templatePorts,omitempty"`
	TemplateType         *string        `json:"templateType,omitempty"`
}

func (o *Template) GetAccessPolicyTemplate() *bool {
	if o == nil {
		return nil
	}
	return o.AccessPolicyTemplate
}

func (o *Template) GetColortokensManaged() *bool {
	if o == nil {
		return nil
	}
	return o.ColortokensManaged
}

func (o *Template) GetTemplateCategory() *string {
	if o == nil {
		return nil
	}
	return o.TemplateCategory
}

func (o *Template) GetTemplateDescription() *string {
	if o == nil {
		return nil
	}
	return o.TemplateDescription
}

func (o *Template) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Template) GetTemplateName() *string {
	if o == nil {
		return nil
	}
	return o.TemplateName
}

func (o *Template) GetTemplatePaths() []TemplatePath {
	if o == nil {
		return nil
	}
	return o.TemplatePaths
}

func (o *Template) GetTemplatePorts() []MetadataPort {
	if o == nil {
		return nil
	}
	return o.TemplatePorts
}

func (o *Template) GetTemplateType() *string {
	if o == nil {
		return nil
	}
	return o.TemplateType
}
