// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Templates struct {
	Items    []TemplateSummary  `json:"items,omitempty"`
	Metadata *PaginationSummary `json:"metadata,omitempty"`
}

func (o *Templates) GetItems() []TemplateSummary {
	if o == nil {
		return nil
	}
	return o.Items
}

func (o *Templates) GetMetadata() *PaginationSummary {
	if o == nil {
		return nil
	}
	return o.Metadata
}
