workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    x-shield-api:
        inputs:
            - location: ./xshield_oas3.yaml
        registry:
            location: registry.speakeasyapi.dev/colortokens/colortokens/x-shield-api
targets:
    xshield-sdk:
        target: terraform
        source: x-shield-api
