// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk"
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/shared"
	"net/http"
)

var _ provider.Provider = &XshieldSDKProvider{}

type XshieldSDKProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// XshieldSDKProviderModel describes the provider data model.
type XshieldSDKProviderModel struct {
	ServerURL types.String `tfsdk:"server_url"`
	Jwt       types.String `tfsdk:"jwt"`
}

func (p *XshieldSDKProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "xshield-sdk"
	resp.Version = p.version
}

func (p *XshieldSDKProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: `ColorTokens Core API: API for managing lifecycle of core micro-segmentation resources (tags, assets & groups)`,
		Attributes: map[string]schema.Attribute{
			"server_url": schema.StringAttribute{
				MarkdownDescription: "Server URL (defaults to https://ng.colortokens.com)",
				Optional:            true,
				Required:            false,
			},
			"jwt": schema.StringAttribute{
				Optional:  true,
				Sensitive: true,
			},
		},
	}
}

func (p *XshieldSDKProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data XshieldSDKProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ServerURL := data.ServerURL.ValueString()

	if ServerURL == "" {
		ServerURL = "https://ng.colortokens.com"
	}

	jwt := new(string)
	if !data.Jwt.IsUnknown() && !data.Jwt.IsNull() {
		*jwt = data.Jwt.ValueString()
	} else {
		jwt = nil
	}
	security := shared.Security{
		Jwt: jwt,
	}

	opts := []sdk.SDKOption{
		sdk.WithServerURL(ServerURL),
		sdk.WithSecurity(security),
		sdk.WithClient(http.DefaultClient),
	}
	client := sdk.New(opts...)

	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *XshieldSDKProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewNamedNetworkResource,
	}
}

func (p *XshieldSDKProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewNamedNetworkDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &XshieldSDKProvider{
			version: version,
		}
	}
}
