// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk"
	"github.com/speakeasy/terraform-provider-xshield-sdk/internal/sdk/models/operations"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &TagRuleDataSource{}
var _ datasource.DataSourceWithConfigure = &TagRuleDataSource{}

func NewTagRuleDataSource() datasource.DataSource {
	return &TagRuleDataSource{}
}

// TagRuleDataSource is the data source implementation.
type TagRuleDataSource struct {
	client *sdk.XshieldSDK
}

// TagRuleDataSourceModel describes the data model.
type TagRuleDataSourceModel struct {
	ID              types.String            `tfsdk:"id"`
	MatchingAssets  types.Int64             `tfsdk:"matching_assets"`
	OnMatch         map[string]types.String `tfsdk:"on_match"`
	RuleCriteria    types.String            `tfsdk:"rule_criteria"`
	RuleDescription types.String            `tfsdk:"rule_description"`
	RuleEnabled     types.Bool              `tfsdk:"rule_enabled"`
	RuleName        types.String            `tfsdk:"rule_name"`
}

// Metadata returns the data source type name.
func (r *TagRuleDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tag_rule"
}

// Schema defines the schema for the data source.
func (r *TagRuleDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "TagRule DataSource",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"matching_assets": schema.Int64Attribute{
				Computed: true,
			},
			"on_match": schema.MapAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},
			"rule_criteria": schema.StringAttribute{
				Computed: true,
			},
			"rule_description": schema.StringAttribute{
				Computed: true,
			},
			"rule_enabled": schema.BoolAttribute{
				Computed: true,
			},
			"rule_name": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (r *TagRuleDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.XshieldSDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.XshieldSDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *TagRuleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *TagRuleDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	var ruleID string
	ruleID = data.ID.ValueString()

	request := operations.GetTagRuleRequest{
		RuleID: ruleID,
	}
	res, err := r.client.Tagrules.GetTagRule(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.TagRule != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedTagRule(res.TagRule)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
