// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type NamednetworkNamedNetwork struct {
	AssignedByTagBasedPolicy              types.Bool          `tfsdk:"assigned_by_tag_based_policy"`
	ID                                    types.String        `tfsdk:"id"`
	IPRanges                              []NamednetworkRange `tfsdk:"ip_ranges"`
	IsOOBNetwork                          types.Bool          `tfsdk:"is_oob_network"`
	NamedNetworkAssignments               types.Int64         `tfsdk:"named_network_assignments"`
	NamedNetworkDescription               types.String        `tfsdk:"named_network_description"`
	NamedNetworkName                      types.String        `tfsdk:"named_network_name"`
	NamednetworkTagBasedPolicyAssignments types.Int64         `tfsdk:"namednetwork_tag_based_policy_assignments"`
	ProgramAsInternet                     types.Bool          `tfsdk:"program_as_internet"`
	ProgramAsIntranet                     types.Bool          `tfsdk:"program_as_intranet"`
	Region                                types.String        `tfsdk:"region"`
	Service                               types.String        `tfsdk:"service"`
	TotalComments                         types.Int64         `tfsdk:"total_comments"`
	TotalCount                            types.Int64         `tfsdk:"total_count"`
	UsergroupNamedNetworkAssignments      types.Int64         `tfsdk:"usergroup_named_network_assignments"`
}
