// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type ReviewCoverage struct {
	Allowed      types.Int64 `tfsdk:"allowed"`
	AllowedPorts types.Int64 `tfsdk:"allowed_ports"`
	Reviewed     types.Int64 `tfsdk:"reviewed"`
	Total        types.Int64 `tfsdk:"total"`
	Unreviewed   types.Int64 `tfsdk:"unreviewed"`
}
