// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type TagBasedPolicyMilestone struct {
	CompletionPercentage types.Number `tfsdk:"completion_percentage"`
	MilestoneID          types.Int64  `tfsdk:"milestone_id"`
	Name                 types.String `tfsdk:"name"`
}
