// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type TemplateReference struct {
	TemplateID   types.String `tfsdk:"template_id"`
	TemplateName types.String `tfsdk:"template_name"`
}
